width = 1200
samples_per_pixel = 10
max_depth = 50

multithread_enabled = true
threads = 8 

[ground]
material = "diffuse"
center = [0.0, -1000.0, 0.0]
color = [0.5, 0.5, 0.5]
radius = 1000.0

[ground.diffuse]
albedo = [0.2, 0.5, 0.3]

[ground.metal]
albedo = [0.5, 0.6, 0.7]
fuzz = 0.3

[ground.dielectric]
refraction = 1.5 


[material]
diffuse_percent = 0.8
metal_percent = 0.15
dielectric_percent = 0.05


